name: Test

on:
  push:

jobs:
  spec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crystal: [1.2, 1.3, 1.4]
      fail-fast: false
    steps:
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Checkout
        uses: actions/checkout@v3
      - run: shards --version
      - run: crystal main.cr
