name: Test

on:
  push:

jobs:
  spec:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: crystal main.cr
